#ifndef LIGHTING_CFG
#define LIGHTING_CFG

#define MAX_NUMBER_OF_SIGNALS 2

#define SENSOR_LEFT_PIN PIN2
#define SENSOR_RIGHT_PIN PIN3

#define LEFT_DEBOUNCE_DELAY 15
#define RIGHT_DEBOUNCE_DELAY 15

#endif